In [27]:
import pandas as pd
import glob
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
def formatter(f):
    year = int(f.split("laucnty")[1][0:2])
    year = year + (2000 if year <16 else 1900 )
    df = pd.read_excel(f,skiprows=5,convert_float=False)
    df.drop(["Unnamed: 5"], axis=1, inplace=True)
    df.columns = ["LAUS", "FIPS_state","FIPS_county", \
                  "county_state", "year", "labor_force","employed", \
                 "unemployed","unemployment_rate"]
    splitNames = df.county_state.str.split(",",expand=True)
    df.FIPS_county = df.FIPS_county.apply('{0:0>3.0f}'.format)
    df.FIPS_state = df.FIPS_state.apply('{0:0>2.0f}'.format)
    df.dropna(inplace=True)
    df.index.name = "index"
    df["county"] = splitNames.loc[:,0].astype("string")
    df["state"] = splitNames.loc[:,1].astype("string")
    df["county"] = df.county.str.split("County",expand=True).loc[:,0].astype("str")
    df.drop(["county_state"],axis=1, inplace=True)
    df.dropna(inplace=True)
    df[["year"]] = int(year)
    df["geoid"] = df.FIPS_state + df.FIPS_county
#     df.to_csv('./data/county-employment/county-' + str(year) + '.csv')
    return df

In [52]:
allFiles = glob.glob("./data/county-employment/*.xlsx")
df = pd.concat([ formatter(f) for f in allFiles ])
# df.to_csv("./data/county-employment/all-years.csv")

In [88]:
la = df[df.year==2015].copy()
# la.unemployed.hist(bins=5)

# la["c"] = la.employed.cumsum()
# la.employed.sort()
la.sort_values(by="employed",inplace=True,axis=0)
# la.reset_index()
la.drop(col)
# plt.plot(la.employed.cumsum()/la.employed.sum())
# p = la.employed.sum()
# s = la.employed.cumsum()
# u = (s/p).copy()
# la["c"] = la.employed.cumsum()/la.employed.sum()
# la.c.plot(kind="line")

,index,LAUS,FIPS_state,FIPS_county,year,labor_force,employed,unemployed,unemployment_rate,county,state,geoid
0,2672,CN4830100000000,48,301,2015,78,74,4,5.1,Loving,TX,48301
1,2656,CN4826900000000,48,269,2015,219,212,7,3.2,King,TX,48269
2,1655,CN3100500000000,31,005,2015,226,216,10,4.4,Arthur,NE,31005
3,94,CN0228200000000,02,282,2015,266,244,22,8.3,Yakutat Borough/city,AK,02282
4,1805,CN3502100000000,35,021,2015,280,256,24,8.6,Harding,NM,35021
5,1657,CN3100900000000,31,009,2015,275,263,12,4.4,Blaine,NE,31009
6,2652,CN4826100000000,48,261,2015,284,276,8,2.8,Kenedy,TX,48261
7,1631,CN3006900000000,30,069,2015,293,278,15,5.1,Petroleum,MT,30069
8,1648,CN3010300000000,30,103,2015,360,342,18,5,Treasure,MT,30103
9,71,CN0206000000000,02,060,2015,390,354,36,9.2,Bristol Bay Borough,AK,02060
10,1427,CN2805500000000,28,055,2015,427,355,72,16.9,Issaquena,MS,28055
11,1710,CN3111500000000,31,115,2015,381,368,13,3.4,Loup,NE,31115
12,1615,CN3003700000000,30,037,2015,401,384,17,4.2,Golden Valley,MT,30037
13,566,CN1603300000000,16,033,2015,406,391,15,3.7,Clark,ID,16033
14,1698,CN3109100000000,31,091,2015,414,397,17,4.1,Hooker,NE,31091
15,2538,CN4803300000000,48,033,2015,414,402,12,2.9,Borden,TX,48033
16,284,CN0807900000000,08,079,2015,437,421,16,3.7,Mineral,CO,08079
17,1690,CN3107500000000,31,075,2015,432,422,10,2.3,Grant,NE,31075
18,2743,CN4844300000000,48,443,2015,446,424,22,4.9,Terrell,TX,48443
19,1656,CN3100700000000,31,007,2015,441,426,15,3.4,Banner,NE,31007
20,1738,CN3117100000000,31,171,2015,439,426,13,3,Thomas,NE,31171
21,271,CN0805300000000,08,053,2015,440,427,13,3,Hinsdale,CO,08053
22,2791,CN4903100000000,49,031,2015,466,436,30,6.4,Piute,UT,49031
23,2718,CN4839300000000,48,393,2015,455,436,19,4.2,Roberts,TX,48393
24,2032,CN3808700000000,38,087,2015,455,443,12,2.6,Slope,ND,38087
25,2780,CN4900900000000,49,009,2015,475,453,22,4.6,Daggett,UT,49009
26,1992,CN3800700000000,38,007,2015,472,458,14,3,Billings,ND,38007
27,300,CN0811100000000,08,111,2015,482,462,20,4.1,San Juan,CO,08111
28,1711,CN3111700000000,31,117,2015,472,463,9,1.9,McPherson,NE,31117
29,2694,CN4834500000000,48,345,2015,485,467,18,3.7,Motley,TX,48345
...,...,...,...,...,...,...,...,...,...,...,...,...
3189,219,CN0606700000000,06,067,2015,688999,647624,41375,6,Sacramento,CA,06067
3190,2293,CN4210100000000,42,101,2015,696194,648280,47914,6.9,Philadelphia,PA,42101
3191,367,CN1209500000000,12,095,2015,688018,654304,33714,4.9,Orange,FL,12095
3192,347,CN1205700000000,12,057,2015,689463,655324,34139,5,Hillsborough,FL,12057
3193,1339,CN2705300000000,27,053,2015,679549,657229,22320,3.3,Hennepin,MN,27053
3194,369,CN1209900000000,12,099,2015,693635,658768,34867,5,Palm Beach,FL,12099
3195,1856,CN3605900000000,36,059,2015,695815,665806,30009,4.3,Nassau,NY,36059
3196,1311,CN2616300000000,26,163,2015,750854,696033,54821,7.3,Wayne,MI,26163
3197,1878,CN3610300000000,36,103,2015,776358,739146,37212,4.8,Suffolk,NY,36103
3198,186,CN0600100000000,06,001,2015,824809,785676,39133,4.7,Alameda,CA,06001
3199,1224,CN2501700000000,25,017,2015,857671,822940,34731,4,Middlesex,MA,25017
3200,2536,CN4802900000000,48,029,2015,874901,841401,33500,3.8,Bexar,TX,48029
3201,221,CN0607100000000,06,071,2015,926641,866793,59848,6.5,San Bernardino,CA,06071
3202,1857,CN3606100000000,36,061,2015,931558,886648,44910,4.8,New York,NY,36061
3203,325,CN1201100000000,12,011,2015,992392,942412,49980,5,Broward,FL,12011
3204,2741,CN4843900000000,48,439,2015,992840,951589,41251,4.2,Tarrant,TX,48439
3205,218,CN0606500000000,06,065,2015,1.03518e+06,965533,69645,6.7,Riverside,CA,06065
3206,228,CN0608500000000,06,085,2015,1.01841e+06,976091,42316,4.2,Santa Clara,CA,06085
3207,1747,CN3200300000000,32,003,2015,1.04753e+06,976263,71265,6.8,Clark,NV,32003
3208,1867,CN3608100000000,36,081,2015,1.18168e+06,1.12281e+06,58871,5,Queens,NY,36081
3209,2968,CN5303300000000,53,033,2015,1.1773e+06,1.12499e+06,52307,4.4,King,WA,53033
3210,1850,CN3604700000000,36,047,2015,1.24293e+06,1.16999e+06,72945,5.9,Kings,NY,36047
3211,2578,CN4811300000000,48,113,2015,1.27404e+06,1.21969e+06,54348,4.3,Dallas,TX,48113
3212,362,CN1208600000000,12,086,2015,1.3344e+06,1.25242e+06,81983,6.1,Miami-Dade,FL,12086
3213,222,CN0607300000000,06,073,2015,1.56384e+06,1.48253e+06,81308,5.2,San Diego,CA,06073
3214,215,CN0605900000000,06,059,2015,1.59707e+06,1.52556e+06,71507,4.5,Orange,CA,06059
3215,103,CN0401300000000,04,013,2015,2.00785e+06,1.90392e+06,103927,5.2,Maricopa,AZ,04013
3216,2622,CN4820100000000,48,201,2015,2.23943e+06,2.13563e+06,103800,4.6,Harris,TX,48201
3217,609,CN1703100000000,17,031,2015,2.64976e+06,2.48817e+06,161588,6.1,Cook,IL,17031
3218,204,CN0603700000000,06,037,2015,5.01171e+06,4.67485e+06,336860,6.7,Los Angeles,CA,06037

In [335]:
df2 = pd.read_csv("./data/county-employment/Gaz_counties_national.txt",sep="\t")
df2.rename(columns={"GEOID":'geoid'},inplace=True)
df2.geoid = df2.geoid.apply('{0:0>5}'.format)
df2.rename(columns={df2.columns[-1]: 'lng',df2.columns[-2]: 'lat'},inplace=True)
df3 = df.merge(df2,on='geoid',how='left')

In [4]:
df = pd.read_csv("./data/county-employment/demographics-2015.csv")